highlighter: none
# excerpt_separator: <!--more-->
# markdown: kramdown
plugins:
  - jekyll-mentions
  # - jekyll-feed
  # - jekyll-seo-tag
  # - jekyll-sitemap
  # - jekyll-avatar

sass:
  load_paths:
    - scss
    # - sass_dir
    # - _sass
    # - node_modules

include:
  - permalink: /404.html
  - assets/js

exclude:
  - node_modules
  - LICENSE
  - Makefile
# - README.md
  - package.json
  - package-lock.json
  - yarn.lock
  - blank.html
  - assets/css/blank.css
  - assets/css/add-style.css
  - assets/vendor/css/materialize.css
  - assets/vendor/js/materialize.js
  - test
  - .eslintrc.js
  - .travis.yml
  - index.js
  - assets/css/prism.css
  # - assets/css/style.css
  # Jekyll local build serve does not like prism.min.js
  - assets/js/prism.min.js
  # - assets/js/script.js.01.bak
  # - assets/js/script.js.02.bak
  # - assets/js/script.js
